Models/Marca.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiPrimeraAplicacionWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marca
    {
        public Marca()
        {
            this.Bus = new HashSet<Bus>();
        }
    
        public int IIDMARCA { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        public virtual ICollection<Bus> Bus { get; set; }
    }
}

Controllers/MarcaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MiPrimeraAplicacionWeb.Models;

namespace MiPrimeraAplicacionWeb.Controllers
{
    public class MarcaController: Controller {
        // GET: Marca
        public ActionResult Index (MarcaCLS marcaCLS) {//Busqueda en el index            
            List<MarcaCLS> listaMarca = null;            
            using (var bd = new BDPasajeEntities()) { 
                if (marcaCLS.nombre == null) {
                    listaMarca = (from marca in bd.Marca
                                  where marca.BHABILITADO == 1
                                  select new MarcaCLS {
                                      iidmarca = marca.IIDMARCA,
                                      nombre = marca.NOMBRE,
                                      descripcion = marca.DESCRIPCION
                                  }).ToList();
                } else {
                    listaMarca = (from marca in bd.Marca
                                  where marca.BHABILITADO == 1 && marca.NOMBRE.Contains(marcaCLS.nombre)
                                  select new MarcaCLS {
                                      iidmarca = marca.IIDMARCA,
                                      nombre = marca.NOMBRE,
                                      descripcion = marca.DESCRIPCION
                                  }).ToList();
                }                
            }
            return View(listaMarca);
        }
        public ActionResult Agregar () {//Este metodo crea la vista
            return View();
        }

        public ActionResult Editar (int id) {
            MarcaCLS oMarcaCLS = new MarcaCLS();
            using (var bd = new BDPasajeEntities()) {                
                Marca oMarca = bd.Marca.Where(p => p.IIDMARCA.Equals(id)).First();
                oMarcaCLS.iidmarca = oMarca.IIDMARCA;
                oMarcaCLS.nombre = oMarca.NOMBRE;
                oMarcaCLS.descripcion = oMarca.DESCRIPCION;                
            }
                return View(oMarcaCLS);
        }

        [HttpPost]
        public ActionResult Editar (MarcaCLS oMarcaCLS) {
            int nregistrosEncontrados = 0;
            using (var bd = new BDPasajeEntities()) {
                nregistrosEncontrados = bd.Marca.Where(p => p.NOMBRE.Equals(oMarcaCLS.nombre) && !p.IIDMARCA.Equals(oMarcaCLS.iidmarca)).Count();
            }
                if (!ModelState.IsValid || nregistrosEncontrados > 0) {
                if (nregistrosEncontrados > 0) oMarcaCLS.mensajeError = "Marca ya existe";
                    return View(oMarcaCLS);
                }
            int idMarca = oMarcaCLS.iidmarca;
            using (var bd = new BDPasajeEntities()) {
                Marca oMarca = bd.Marca.Where(p => p.IIDMARCA == idMarca).First();
                oMarca.NOMBRE = oMarcaCLS.nombre;
                oMarca.DESCRIPCION = oMarcaCLS.descripcion;
                bd.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Agregar (MarcaCLS oMarcaCLS) {//Este metodo ejecuta la insercion
            int nregistrosEncontrados = 0;
            string nombreMarca = oMarcaCLS.nombre;
            using (var bd = new BDPasajeEntities()) {
                nregistrosEncontrados = bd.Marca.Where(p => p.NOMBRE.Equals(nombreMarca)).Count();
            }
                if (!ModelState.IsValid || nregistrosEncontrados > 0) {
                if (nregistrosEncontrados > 0) oMarcaCLS.mensajeError = "El nombre marca ya existe";
                    return View(oMarcaCLS);
                } else {
                    using (var bd = new BDPasajeEntities()) {
                        Marca oMarca = new Marca();
                        oMarca.NOMBRE = oMarcaCLS.nombre;
                        oMarca.DESCRIPCION = oMarcaCLS.descripcion;
                        oMarca.BHABILITADO = 1;
                        bd.Marca.Add(oMarca);
                        bd.SaveChanges();
                    }

                }
            return RedirectToAction("Index");
        }
        public ActionResult Eliminar (int id) {
            using (var bd = new BDPasajeEntities()) {
                Marca oMarca = bd.Marca.Where(p => p.IIDMARCA == id).First();
                oMarca.BHABILITADO = 0;
                bd.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

Views/Marca/Agregar.cshtml
@using MiPrimeraAplicacionWeb.Models
@model MarcaCLS
@{
    ViewBag.Title = "Agregar";
}

<h2>Agregar Marca</h2>
<!--Nombre Accion, Nombre controlador, Metodo por el que se envia la informacion-->
<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Agregar", "Marca", FormMethod.Post, new { @id="frmAgregar"})) {//Metodo que inserta
            <div>
                @Html.LabelFor(p => p.nombre)
                @Html.TextBoxFor(p => p.nombre, new { @class = "form-control" })
                @Html.ValidationMessage("nombre", new { @class = "text-danger"})<!--Agrega mensaje de error, en caso de mala captura-->
                @if (Model!=null && Model.mensajeError != null) { 
                    @Html.Label(Model.mensajeError, new { @class="text-danger"})
                } 
            </div>
            <div>
                @Html.LabelFor(p => p.descripcion)
                @Html.TextBoxFor(p => p.descripcion, new { @class = "form-control" })
                @Html.ValidationMessage("descripcion", new { @class= "text-danger"})
            </div>
            <br/>
            <div>
                <input type="submit" class="btn btn-primary" value="Guardar"/>
                @Html.ActionLink("Regresar","Index","Marca", null, new { @class="btn btn-danger"})
            </div>
        }
    </div>
</div>
<script>
    var frmAgregar = document.getElementById("frmAgregar");
    frmAgregar.onsubmit = function (e) {
        e.preventDefault();
        if (confirm("Agregar Registro?") == 1) {
            frmAgregar.submit();
        }
    }
</script>

Views/Marca/Editar.cshtml
@using MiPrimeraAplicacionWeb.Models;
@model MarcaCLS
@{
    ViewBag.Title = "Editar";
}

<h2>Editar Marca</h2>
<!--Nombre Accion, Nombre controlador, Metodo por el que se envia la informacion-->
<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Editar", "Marca", FormMethod.Post, new { @id="frmEditar"})) {
            <div>
                @Html.LabelFor(p => p.iidmarca)
                @Html.TextBoxFor(p => p.iidmarca, new { @class = "form-control", @readOnly=true})
                @Html.ValidationMessage("iidmarca", new { @class = "text-danger" })<!--Agrega mensaje de error, en caso de mala captura-->              
            </div>
            <div>
                @Html.LabelFor(p => p.nombre)
                @Html.TextBoxFor(p => p.nombre, new { @class = "form-control" })
                @Html.ValidationMessage("nombre", new { @class = "text-danger" })<!--Agrega mensaje de error, en caso de mala captura-->
                @if (Model != null && Model.mensajeError != null) {
                    @Html.Label(Model.mensajeError, new { @class = "text-danger" })
                }
            </div>
            <div>
                @Html.LabelFor(p => p.descripcion)
                @Html.TextBoxFor(p => p.descripcion, new { @class = "form-control" })
                @Html.ValidationMessage("descripcion", new { @class = "text-danger" })
            </div>
            <br />
            <div>
                <input type="submit" class="btn btn-primary" value="Guardar" />
                @Html.ActionLink("Regresar", "Index", "Marca", null, new { @class ="btn btn-danger" })
            </div>
        }
    </div>
</div>
<script>
    var frmEditar = document.getElementById("frmEditar");
    frmEditar.onsubmit = function (e) {
        e.preventDefault();
        if (confirm("Guardar cambios?") == 1) {
            frmEditar.submit();
        }
    }
</script>

Views/Marca/Index.cshtml
@using MiPrimeraAplicacionWeb.Models
@model List<MarcaCLS>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<!--Actiuonlink(Nombre del boton, Nombre de la accion, Nombre del controlador)-->
@Html.ActionLink("Agregar","Agregar", "Marca", null, new { @class = "btn btn-primary" })
<table class="table table-bordered table-striped"><!--Crear tabla (con Boostrap)-->
    <thead><!--Crear cabecera-->
        <tr>
            <!--Crear fila-->
            <td width="10%">@Html.LabelFor(p=>Model[0].iidmarca)</td>
            <td width="20%">@Html.LabelFor(p=>Model[0].nombre)</td>
            <td width="70%">@Html.LabelFor(p=>Model[0].descripcion)</td>            
        </tr>

    </thead>
    <tbody><!--Cuerpo de la tabla-->
        
        @foreach (var item in Model) { //Retorna cada objeto en la lista(Model)
        <tr>
            <!--Registros de la tabla-->
            <td>@item.iidmarca</td>
            <td>@item.nombre</td>
            <td>@item.descripcion</td>
        </tr>
        }        
    </tbody>
</table>