Models/Bus.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiPrimeraAplicacionWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus
    {
        public Bus()
        {
            this.DETALLEVENTA = new HashSet<DETALLEVENTA>();
            this.Viaje = new HashSet<Viaje>();
        }
    
        public int IIDBUS { get; set; }
        public Nullable<int> IIDSUCURSAL { get; set; }
        public Nullable<int> IIDTIPOBUS { get; set; }
        public string PLACA { get; set; }
        public Nullable<System.DateTime> FECHACOMPRA { get; set; }
        public Nullable<int> IIDMODELO { get; set; }
        public Nullable<int> NUMEROFILAS { get; set; }
        public Nullable<int> NUMEROCOLUMNAS { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
        public string DESCRIPCION { get; set; }
        public string OBSERVACION { get; set; }
        public Nullable<int> IIDMARCA { get; set; }
    
        public virtual Marca Marca { get; set; }
        public virtual Modelo Modelo { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual TipoBus TipoBus { get; set; }
        public virtual ICollection<DETALLEVENTA> DETALLEVENTA { get; set; }
        public virtual ICollection<Viaje> Viaje { get; set; }
    }
}

Controllers/BusController.cs
using MiPrimeraAplicacionWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace MiPrimeraAplicacionWeb.Controllers
{
    public class BusController : Controller
    {
        [HttpPost]
        public ActionResult Eliminar (int iidBus) {
            using (var bd = new BDPasajeEntities()) {
                Bus oBus = bd.Bus.Where(p => p.IIDBUS.Equals(iidBus)).First();
                oBus.BHABILITADO = 0;
                bd.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public void listarCombos () {
            listarTipoBus();
            listarSucursal();
            listarModelo();
            listarMarca();
        }
        public ActionResult Editar (int id) {
            BusCLS oBusCls = new BusCLS();
            listarCombos();
            using (var bd = new BDPasajeEntities()) {//No regresa informacion
                Bus oBus = bd.Bus.Where(p => p.IIDBUS.Equals(id)).First();
                oBusCls.iidBus = oBus.IIDBUS;
                oBusCls.iidSucursal = (int)oBus.IIDSUCURSAL;
                oBusCls.iidTipoBus = (int)oBus.IIDTIPOBUS;
                oBusCls.iidModelo = (int)oBus.IIDMODELO;
                oBusCls.iidMarca = (int)oBus.IIDMARCA;
                oBusCls.placa = oBus.PLACA;
                oBusCls.fechaCompra = (DateTime)oBus.FECHACOMPRA;                
                oBusCls.numeroColumnas = (int)oBus.NUMEROCOLUMNAS;
                oBusCls.numeroFilas = (int)oBus.NUMEROFILAS;
                oBusCls.descripcion = oBus.DESCRIPCION;
                oBusCls.observacion = oBus.OBSERVACION;                

            }
                return View(oBusCls);
        }
        [HttpPost]
        public ActionResult Editar (BusCLS oBusCLS) {
            int nRegistros = 0;
            int idBus = oBusCLS.iidBus;
            string placa = oBusCLS.placa;

            using (var bd = new BDPasajeEntities()) {
                nRegistros = bd.Bus.Where(p => p.PLACA.Equals(placa) && !p.IIDBUS.Equals(idBus)).Count();
            }
            if (!ModelState.IsValid || nRegistros > 0) {
                if (nRegistros > 0) oBusCLS.mensajeError = "El Bus ya existe";
                listarCombos();
                return View(oBusCLS);
            }
            
            using (var bd = new BDPasajeEntities()) {
                Bus oBus = bd.Bus.Where(p => p.IIDBUS == idBus).First();
                oBus.IIDSUCURSAL = oBusCLS.iidSucursal;
                oBus.IIDMODELO = oBusCLS.iidModelo;
                oBus.IIDMARCA = oBusCLS.iidMarca;
                oBus.IIDTIPOBUS = oBusCLS.iidTipoBus;
                oBus.FECHACOMPRA = oBusCLS.fechaCompra;
                oBus.DESCRIPCION = oBusCLS.descripcion;
                oBus.PLACA = oBusCLS.placa;
                oBus.NUMEROFILAS = oBusCLS.numeroFilas;
                oBus.NUMEROCOLUMNAS = oBusCLS.numeroColumnas;
                oBus.DESCRIPCION = oBusCLS.descripcion;
                oBus.OBSERVACION = oBusCLS.observacion;
                bd.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public ActionResult Agregar () {
            listarCombos();
            return View();
        }
        [HttpPost]
        public ActionResult Agregar (BusCLS oBusCLS) {

            int nRegistros = 0;
            string placa = oBusCLS.placa;
            
            using (var bd = new BDPasajeEntities()) {
                
                nRegistros = bd.Bus.Where(p => p.PLACA.Equals(placa)).Count();
            }
                if (!ModelState.IsValid || nRegistros > 0) {
                if (nRegistros > 0) oBusCLS.mensajeError = "Ya Existe el Bus";
                    listarCombos();
                    return View(oBusCLS);
                }
            using (var bd = new BDPasajeEntities()) {
                Bus oBus = new Bus();
                oBus.IIDSUCURSAL = oBusCLS.iidSucursal;                
                oBus.IIDMARCA = oBusCLS.iidMarca;                
                oBus.IIDMODELO = oBusCLS.iidModelo;                
                oBus.IIDTIPOBUS = oBusCLS.iidTipoBus;  
                oBus.PLACA = oBusCLS.placa;
                oBus.FECHACOMPRA = oBusCLS.fechaCompra;
                oBus.NUMEROCOLUMNAS = oBusCLS.numeroColumnas;
                oBus.NUMEROFILAS = oBusCLS.numeroFilas;
                oBus.DESCRIPCION = oBusCLS.descripcion;
                oBus.OBSERVACION = oBusCLS.observacion;                
                oBus.BHABILITADO = 1;
                bd.Bus.Add(oBus);
                bd.SaveChanges();

            }
            return RedirectToAction("Index");
        }
        // GET: Bus
        public ActionResult Index(BusCLS busCLS)
        {
            listarCombos();
            List<BusCLS> listaBus = null;
            List<BusCLS> listaRespuesta = new List<BusCLS>();
            using (var bd = new BDPasajeEntities()) {
                listaBus = (from bus in bd.Bus
                            join sucursal in bd.Sucursal
                            on bus.IIDSUCURSAL equals sucursal.IIDSUCURSAL
                            join tipoBus in bd.TipoBus
                            on bus.IIDTIPOBUS equals tipoBus.IIDTIPOBUS
                            join tipoModelo in bd.Modelo
                            on bus.IIDMODELO equals tipoModelo.IIDMODELO
                            where bus.BHABILITADO == 1
                            select new BusCLS {
                                iidBus = bus.IIDBUS,
                                placa = bus.PLACA,
                                nombreModelo = tipoModelo.NOMBRE,
                                nombreSucursal = sucursal.NOMBRE,
                                nombreTipoBus = tipoBus.NOMBRE,
                                iidModelo = tipoModelo.IIDMODELO,
                                iidSucursal = sucursal.IIDSUCURSAL,
                                iidTipoBus = tipoBus.IIDTIPOBUS
                            }
                               ).ToList();
                if (busCLS.iidBus == 0
                && busCLS.placa == null
                && busCLS.iidModelo == 0
                && busCLS.iidSucursal == 0
                && busCLS.iidTipoBus == 0) {
                    listaRespuesta = listaBus;
                } else {
                    //Filtros
                    if (busCLS.iidBus != 0) {
                        listaBus = listaBus.Where(p => p.iidBus.ToString().Contains(busCLS.iidBus.ToString())).ToList();
                    }
                    if (busCLS.placa != null) {
                        listaBus = listaBus.Where(p => p.placa.Contains(busCLS.placa)).ToList();
                    }
                    if (busCLS.iidModelo != 0) {
                        listaBus = listaBus.Where(p => p.iidModelo.ToString().Contains(busCLS.iidModelo.ToString())).ToList();
                    }
                    if (busCLS.iidSucursal != 0) {
                        listaBus = listaBus.Where(p => p.iidSucursal.ToString().Contains(busCLS.iidSucursal.ToString())).ToList();
                    }
                    if (busCLS.iidTipoBus != 0) {
                        listaBus = listaBus.Where(p => p.iidTipoBus.ToString().Contains(busCLS.iidTipoBus.ToString())).ToList();
                    }
                    listaRespuesta = listaBus;
                }
            }
            return View(listaRespuesta);
        }
        public void listarTipoBus () {
            List<SelectListItem> lista;
            using (var bd = new BDPasajeEntities()) {
                lista = (from item in bd.TipoBus
                         where item.BHABILITADO == 1
                         select new SelectListItem {
                             Text = item.NOMBRE,                             
                             Value = item.IIDTIPOBUS.ToString()
                         }).ToList();
                lista.Insert(0, new SelectListItem { Text = "--Seleccione--", Value = "" });
                ViewBag.listaTipoBus = lista;
            }
        }
        public void listarMarca () {
            List<SelectListItem> lista;
            using (var bd = new BDPasajeEntities()) {
                lista = (from item in bd.Marca
                         where item.BHABILITADO == 1
                         select new SelectListItem {
                             Text = item.NOMBRE,                            
                             Value = item.IIDMARCA.ToString()
                         }).ToList();
                lista.Insert(0, new SelectListItem { Text = "--Seleccione--", Value = "" });
                ViewBag.listaMarca = lista;
            }
        }
        public void listarModelo () {
            List<SelectListItem> lista;
            using (var bd = new BDPasajeEntities()) {
                lista = (from item in bd.Modelo
                         where item.BHABILITADO == 1
                         select new SelectListItem {
                             Text = item.NOMBRE,                             
                             Value = item.IIDMODELO.ToString()
                         }).ToList();
                lista.Insert(0, new SelectListItem { Text = "--Seleccione--", Value = "" });
                ViewBag.listaModelo = lista;
            }
        }
        public void listarSucursal () {
            List<SelectListItem> lista;
            using (var bd = new BDPasajeEntities()) {
                lista = (from item in bd.Sucursal
                         where item.BHABILITADO == 1
                         select new SelectListItem {
                             Text = item.NOMBRE,                             
                             Value = item.IIDSUCURSAL.ToString()

Views/Bus/Agregar.cshtml
@using MiPrimeraAplicacionWeb.Models
@model BusCLS
@{
    ViewBag.Title = "Agregar";
    List<SelectListItem> listaTipoBus = (List<SelectListItem>)ViewBag.listaTipoBus;
    List<SelectListItem> listaMarca = (List<SelectListItem>)ViewBag.listaMarca;
    List<SelectListItem> listaModelo = (List<SelectListItem>)ViewBag.listaModelo;
    List<SelectListItem> listaSucursal = (List<SelectListItem>)ViewBag.listaSucursal;
}

<h2>Agregar Bus</h2>
<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Agregar", "Bus", FormMethod.Post, new { @id="frmAgregar"})) {              
            <div>
                @Html.LabelFor(p => p.iidSucursal)                
                @Html.DropDownList("iidSucursal", listaSucursal, null, new { @class = "form-control" })
                @Html.ValidationMessage("iidSucursal", new { @class = "text-danger" })
            </div>            
            <div>
                @Html.LabelFor(p => p.placa)                
                @Html.TextBoxFor(p => p.placa, new { @class = "form-control" })
                @Html.ValidationMessage("placa", new { @class = "text-danger" })
                @if (Model != null && Model.mensajeError != null) { 
                    @Html.Label(Model.mensajeError, new {@class="text-danger"})
                }
            </div>            
            <div>
                @Html.LabelFor(p => p.iidTipoBus)                
                @Html.DropDownList("iidTipoBus", listaTipoBus, null, new { @class = "form-control" })
                @Html.ValidationMessage("iidTipoBus", new { @class = "text-danger" })                
            </div>
            <div>
                @Html.LabelFor(p => p.fechaCompra)                
                @Html.EditorFor(p => p.fechaCompra, new { @class = "form-control" })
                @Html.ValidationMessage("fechaCompra", new { @class = "text-danger" })                
            </div>
            <div>
                @Html.LabelFor(p => p.iidModelo)
                @Html.DropDownList("iidModelo", listaModelo, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(p => p.iidModelo, "", new { @class = "text-danger" })                
            </div>
            <div>
                @Html.LabelFor(p => p.numeroFilas)                
                @Html.EditorFor(p => p.numeroFilas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(p => p.numeroFilas, "", new { @class = "text-danger" })                
            </div>
            <div>
                @Html.LabelFor(p => p.numeroColumnas)                
                @Html.EditorFor(p => p.numeroColumnas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(p => p.numeroColumnas, "", new { @class = "text-danger" })               
            </div>
            <div>
                @Html.LabelFor(p => p.descripcion)                
                @Html.EditorFor(p => p.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(p => p.descripcion, "", new { @class = "text-danger" })                
            </div>
            <div>
                @Html.LabelFor(p => p.observacion)                
                @Html.EditorFor(p => p.observacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(p => p.observacion, "", new { @class = "text-danger" })                
            </div>
            <div>
                @Html.LabelFor(p => p.iidMarca)                
                @Html.DropDownList("iidMarca", listaMarca, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(p => p.iidMarca, "", new { @class = "text-danger" })                
            </div>
            <div style="margin:auto">                
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                    Guardar
                </button>
                @Html.ActionLink("Regresar", "Index", "Bus", null, new { @class = "btn btn-danger" })
            </div>
            }
        </div>
</div>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Guardar los cambios?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div style="padding:1em">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-info" onclick="Agregar()">Aceptar</button>
            </div>
        </div>
    </div>
</div>
<script>
    function Agregar() {
        var frmAgregar = document.getElementById("frmAgregar");
        frmAgregar.submit();
    }
</script>


Views/Bus/Editar.cshtml
@using MiPrimeraAplicacionWeb.Models
@model BusCLS
@{
    ViewBag.Title = "Editar";
    List<SelectListItem> listaTipoBus = (List<SelectListItem>)ViewBag.listaTipoBus;
    List<SelectListItem> listaMarca = (List<SelectListItem>)ViewBag.listaMarca;
    List<SelectListItem> listaModelo = (List<SelectListItem>)ViewBag.listaModelo;
    List<SelectListItem> listaSucursal = (List<SelectListItem>)ViewBag.listaSucursal;
}

<h2>Editar</h2>
<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Editar", "Bus", FormMethod.Post, new { @id = "frmEditar" })) {
            <div>
                @Html.LabelFor(model => model.iidBus)
                @Html.EditorFor(model => model.iidBus, new { htmlAttributes = new { @class = "form-control", @readOnly = true } })
                @Html.ValidationMessageFor(model => model.iidBus, "", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(model => model.iidSucursal)
                @Html.DropDownList("iidSucursal", listaSucursal, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.iidSucursal, "", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(model => model.placa)
                @Html.EditorFor(model => model.placa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.placa, "", new { @class = "text-danger" })
                @if (Model != null && Model.mensajeError != null) {
                    @Html.Label(Model.mensajeError, new { @class = "text-danger" })
                }
            </div>
            <div>
                @Html.LabelFor(model => model.iidTipoBus)
                @Html.DropDownList("iidTipoBus", listaTipoBus, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.iidTipoBus, "", new { @class = "text-danger" })
            </div>

            <div>
                @Html.LabelFor(model => model.fechaCompra)
                @Html.EditorFor(model => model.fechaCompra, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fechaCompra, "", new { @class = "text-danger" })
            </div>

            <div>
                @Html.LabelFor(model => model.iidModelo)
                @Html.DropDownList("iidModelo", listaModelo, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.iidModelo, "", new { @class = "text-danger" })
            </div>

            <div>
                @Html.LabelFor(model => model.numeroFilas)
                @Html.EditorFor(model => model.numeroFilas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.numeroFilas, "", new { @class = "text-danger" })
            </div>

            <div>
                @Html.LabelFor(model => model.numeroColumnas)
                @Html.EditorFor(model => model.numeroColumnas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.numeroColumnas, "", new { @class = "text-danger" })
            </div>

            <div>
                @Html.LabelFor(model => model.descripcion)
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>

            <div>
                @Html.LabelFor(model => model.observacion)
                @Html.EditorFor(model => model.observacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.observacion, "", new { @class = "text-danger" })
            </div>

            <div>
                @Html.LabelFor(model => model.iidMarca)
                @Html.DropDownList("iidMarca", listaMarca, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.iidMarca, "", new { @class = "text-danger" })
            </div>

            <div>
                @Html.LabelFor(model => model.nombreModelo)
                @Html.EditorFor(model => model.nombreModelo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombreModelo, "", new { @class = "text-danger" })
            </div>
            <div style="margin:auto">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                    Guardar
                </button>
                @Html.ActionLink("Regresar", "Index", "Bus", null, new { @class = "btn btn-danger" })
            </div>
        }
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Guardar los cambios?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div style="padding:1em">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-info" onclick="Editar()">Aceptar</button>
            </div>
        </div>
    </div>
</div>
<script>
    function Editar() {
        var frmEditar = document.getElementById("frmEditar");
        frmEditar.submit();
    }
</script>



Views/Bus/Index.cshtml
@using MiPrimeraAplicacionWeb.Models
@model List<BusCLS>
@{
    ViewBag.Title = "Index";
    List<SelectListItem> listaTipoBus = (List<SelectListItem>)ViewBag.listaTipoBus;
    List<SelectListItem> listaMarca = (List<SelectListItem>)ViewBag.listaMarca;
    List<SelectListItem> listaModelo = (List<SelectListItem>)ViewBag.listaModelo;
    List<SelectListItem> listaSucursal = (List<SelectListItem>)ViewBag.listaSucursal;
}

<h2>Index</h2>
@Html.ActionLink("Agregar", "Agregar", "Bus", new { @class = "btn btn-primary " })


@using (Html.BeginForm("Index", "Bus", FormMethod.Post, new { @id="frmFiltrado"})) {<!--BeginForm(Accion, controller, metodo de envio)-->
    <table class="table table-hover table-bordered">
        <thead>
            <tr>
                <td>@Html.LabelFor(p => Model[0].iidBus)</td>
                <td>@Html.LabelFor(p => Model[0].placa)</td>
                <td>@Html.LabelFor(p => Model[0].nombreModelo)</td>
                <td>@Html.LabelFor(p => Model[0].nombreSucursal)</td>
                <td>@Html.LabelFor(p => Model[0].nombreTipoBus)</td>
                <td>Operaciones</td>
            </tr>
            <tr>
                <td>@Html.TextBox("iidBus", null, new { @class = "form-control" })</td>
                <td>@Html.TextBox("placa", null, new { @class = "form-control" })</td>
                <td>@Html.DropDownList("iidModelo", listaModelo, null, new { @class = "form-control" })</td>
                <td>@Html.DropDownList("iidSucursal", listaSucursal, null, new { @class = "form-control" })</td>
                <td>@Html.DropDownList("iidTipoBus", listaTipoBus, null, new { @class = "form-control" })</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model) {
                <tr>
                    <td>@item.iidBus</td>
                    <td>@item.placa</td>
                    <td>@item.nombreModelo</td>
                    <td>@item.nombreSucursal</td>
                    <td>@item.nombreTipoBus</td>
                    <td>
                        @Html.ActionLink(" ", "Editar", "Bus", new { id = @item.iidBus }, new { @class = "glyphicon glyphicon-edit btn btn-primary" })
                        <button type="button" onclick="mostrarPopup(@item.iidBus)" class="glyphicon glyphicon-trash btn btn-danger" data-toggle="modal" data-target="#exampleModal">
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>

}
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Guardar los cambios?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div style="padding:1em">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-info" onclick="Eliminar()">Aceptar</button>
            </div>
        </div>
    </div>
</div>
@using (Html.BeginForm("Eliminar", "Bus", FormMethod.Post, new { @id = "frmEliminar" })) {
    @Html.Hidden("iidBus");
}
<script>
    var frmFiltrado = document.getElementById("frmFiltrado");
    var controles = document.getElementsByClassName("form-control");
    for (var i = 0; i < controles.length; i++) {
        controles[i].onchange = function () {
            frmFiltrado.submit();
        }
    }

    function mostrarPopup(idBus) {
        document.getElementById("iidBus").value = idBus;
    }
    function Eliminar() {
        var frmEliminar = document.getElementById("frmEliminar");
        frmEliminar.submit();
    }
</script>
